# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: v2.17.1@sha256:112abf6fa1ce352acb7fd96f14eaef3d5d8cda2906e59448bf8fb13b74ad10c1
workload:
  main:
    podSpec:
      containers:
        main:
          command:
            - python
            - Tautulli.py
          args:
            - --config
            - /config/config.ini
            - --datadir
            - /config
service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181
persistence:
  config:
    enabled: true
    mountPath: "/config"
