# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/brandawg93/peanut
  tag: 6.0.0@sha256:6629dce915da8b313f08b2e73dd2e54b60e7c0f642c21a8ebc37fe0a820bf41e
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688

persistence:
  config:
    enabled: true
    mountPath: "/config"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
