# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: 2.1.0@sha256:7c60eb0ec887696c8684de88aea2dfe39a7391184b29d33c0aad778c99c7683e
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /rest/noauth/health
            readiness:
              path: /rest/noauth/health
            startup:
              path: /rest/noauth/health
service:
  main:
    ports:
      main:
        port: 8384
        targetPort: 8384
  listeners:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 22000
        targetPort: 22000
  listeners-udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 22000
        targetPort: 22000
        protocol: udp
  discovery:
    enabled: true
    ports:
      discovery:
        enabled: true
        port: 21027
        targetPort: 21027
        protocol: udp
persistence:
  config:
    enabled: true
    mountPath: "/var/syncthing"
