# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/benzino77/tasmocompiler
  tag: latest@sha256:f924035be9928c9b01fe14130a2f6e72b71c9d617269fd4fc82d5cac053962ff
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 14003
        protocol: http
        targetPort: 3000
