# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/freshrss
  pullPolicy: IfNotPresent
  tag: 1.29.0@sha256:9ea33a3b660f1e8485867374be36d39898c7b43fcbd2595e2442cb1d9b23410e
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10010
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
