# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/sirfragalot/hyperion.ng
  tag: 2.2.0@sha256:1848762c12cdd24a29dc311f100ee9f864f813c9d3b2aacf0b1e3f7876117e55
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10065
        targetPort: 8090
  jsonservice:
    enabled: true
    ports:
      jsonservice:
        enabled: true
        port: 19444
        targetPort: 19444
  protobufservice:
    enabled: true
    ports:
      protobufservice:
        enabled: true
        port: 19445
        targetPort: 19445
  boblightservice:
    enabled: true
    ports:
      boblightservice:
        enabled: true
        port: 19333
        targetPort: 19333
persistence:
  config:
    enabled: true
    mountPath: "/root/.hyperion"

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
