# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/nzbget
  pullPolicy: IfNotPresent
  tag: "26.1.0@sha256:182a53d568b6c3b01242e5332d7ee6e4d37dd1f4854b0342714864f8da3c15c7"
service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789
persistence:
  config:
    enabled: true
    mountPath: "/config"

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
