# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/sysadminsmedia/homebox
  pullPolicy: IfNotPresent
  tag: 0.25.0@sha256:6506480a3dfadd2cc885fa97b32d11b0ee28ec58629fa34a76afdb4ac540c7fc
homebox:
  allow_registration: true
  auto_increment_asset_id: true
  max_upload_size: 10
  log_level: info
  log_format: text
  mailer_host: ""
  mailer_port: 587
  mailer_from: ""
  mailer_username: ""
  mailer_password: ""
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: homebox-secret
service:
  main:
    ports:
      main:
        protocol: http
        port: 10603
persistence:
  data:
    enabled: true
    mountPath: /data
