# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/lswl/vertex
  tag: stable@sha256:02e418aaf94abc4a8f3390b627efe406d977d1e8c62e89e44627f63b076b3edc
persistence:
  config:
    enabled: true
    mountPath: /vertex

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "3000"
