# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/kasmweb/workspaces
  tag: 1.18.1@sha256:6788f812245cbd9a705c0df696bb56b88586056d48bc21d953f1e3a17f7c2321
kasm:
  mountUdev: false
  mountInput: false
service:
  main:
    ports:
      main:
        port: 10350
        protocol: https
  admin:
    enabled: true
    ports:
      admin:
        enabled: true
        port: 10351
        protocol: https
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /opt
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    privileged: true
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: https
              path: /
              port: "{{ .Values.service.admin.ports.admin.targetPort }}"
            readiness:
              type: https
              path: /
              port: "{{ .Values.service.admin.ports.admin.targetPort }}"
            startup:
              type: https
              path: /
              port: "{{ .Values.service.admin.ports.admin.targetPort }}"
          env:
            KASM_PORT: "{{ .Values.service.main.ports.main.port }}"
            DOCKER_HUB_PASSWORD: ""
            DOCKER_HUB_USERNAME: ""
