# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/victoriametrics/victoria-metrics
  tag: v1.143.0@sha256:59b229f9b5ac32bb28c5ad94fc3019e34e82a3137f27f6ede6f73edeeefc2c64
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8428
        targetPort: 8428
persistence:
  data:
    enabled: true
    mountPath: /victoria-metrics-data
    targetSelectAll: true

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /health
            readiness:
              type: http
              path: /health
            startup:
              enabled: false
