# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/coderaiser/cloudcmd
  tag: 19.17.0@sha256:af87e0b09b61b1bdb88c2649cb77087af9d377f59077189a3374fd57668e1845
persistence:
  appdata:
    enabled: true
    mountPath: /root
  mountpath:
    enabled: true
    mountPath: /UNRAID

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8765
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /root
