# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/bndw/wifi-card
  tag: latest@sha256:0cb0bdebcc58641a30d2c8d5de2646955bcad0ddb7fbd102928d6ae646a26797

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 80
        port: 8888
