# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/calibre-web
  pullPolicy: IfNotPresent
  tag: "0.6.26@sha256:e51f69c1758a4842dd8313947eeb0bcbe470a257e15bedcd6b158c97d659a97b"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8083
        protocol: http
        targetPort: 8083
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
