# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/jellyseerr
  tag: "2.7.3@sha256:8d266530eaee828b54552981a244614bd5d8ba3dca143a779538c78e3c435e6b"
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10241
persistence:
  config:
    enabled: true
    mountPath: "/app/config"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # User Defined
            JELLYFIN_TYPE: ""
            LOG_LEVEL: "info"
