# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ombi
  pullPolicy: IfNotPresent
  tag: 4.53.5@sha256:2a1edf438ebfc4f1aae148c32914d7d7c1ba4c92923b32fed7a19d03933812ed
service:
  main:
    ports:
      main:
        port: 3579
        targetPort: 3579
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true
