# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/pykmsorg/py-kms
  pullPolicy: IfNotPresent
  tag: minimal@sha256:d6e0989ae210c203c8e0d56638344219a5e5f27d088e816b910b6fdde935dd8c
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            startup:
              type: tcp
            readiness:
              type: tcp
service:
  main:
    ports:
      main:
        port: 1688
        targetPort: 1688
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
