# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cglatot/pasta
  pullPolicy: IfNotPresent
  tag: 2.2.11@sha256:543155ea4e5d5a8c4354e2ad8a28559c9e7d150e939b34f6babb52624c998448
service:
  main:
    ports:
      main:
        port: 10302
        protocol: http
        targetPort: 80

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
