# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/cops
  tag: 4.3.3@sha256:f45c328aec047f6268edf1f0ad5549bae93434bd28cf02fbe418e9c0034f6edb
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10609
        protocol: http
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
  books:
    enabled: true
    mountPath: /books
