# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/accetto/ubuntu-vnc-xfce-blender-g3
  tag: latest@sha256:5231b8ebd1f6c84c9518d43384a791efb89b9c8336a8b9c2ace560be3d8cd037
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
  storageprojects:
    enabled: true
    mountPath: /srv/projects

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: tcp
        targetPort: 5901
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PW: unraid
            VNC_RESOLUTION: 1360x768
