# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/kdenlive
  tag: latest@sha256:6f60d51ddad8ea2ac3756757998aabaf9d6a42540da06e63d2fef3a59c7771fe
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            KEYBOARD: ""
            SUBFOLDER: ""
