# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/lazylibrarian
  pullPolicy: IfNotPresent
  tag: 7.0.0@sha256:0a1cf8124a6e3a8f07f2b7bc5e26ccb4fa10495dbf1eb47f02fa288740122eef
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
