# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/homarr-labs/homarr
  tag: v1.61.0@sha256:6a726c72b37d56a7ce271d35498712f90bfd05ee203bc81e069d718489c35b06
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_ENCRYPTION_KEY: "changemeplease"
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  appdata:
    enabled: true
    mountPath: "/appdata"
  varrun:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
