# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ich777/vintagestory
  tag: latest@sha256:c2a3381deea8ee1c29d4c258825f241ea12c417456174a11c23f76a504a6fef9
persistence:
  serverfiles:
    enabled: true
    mountPath: /vintagestory

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 42420
        protocol: tcp
        targetPort: 42420
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_PARAMS: ""
            VS_CHANNEL: stable@sha256:f0065aa44fb1c38b7fc30d34e220138dc0a0c6477b78eb7f59015622c2052030
