# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/miniflux/miniflux
  tag: 2.3.0@sha256:65266db84761d09d999946218adfc91fd7abbd4a1086f74b3ad0e51083e30df2
persistence:
  config:
    enabled: true
    mountPath: /config

cnpg:
  main:
    enabled: true
    database: miniflux
    user: miniflux
service:
  main:
    ports:
      main:
        port: 10091
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CREATE_ADMIN: 1
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            RUN_MIGRATIONS: 1
            ADMIN_PASSWORD: changeme
            ADMIN_USERNAME: admin
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 3
                httpGet:
                  path: /healthcheck
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 1
