# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/maintainerr/maintainerr
  pullPolicy: IfNotPresent
  tag: 3.11.2@sha256:bd71ca33bc1133437adf4bc4f4c074e1fc2905c5a6c640aa237cfe14d0f249db

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 6246
        port: 6246

persistence:
  data:
    enabled: true
    mountPath: "/opt/data"
