# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/oscam
  pullPolicy: IfNotPresent
  tag: 11960-ls15@sha256:3833f238f8a59d41794a497d9a8e1f54932c88955733082d3b92ada4f113565b
service:
  main:
    ports:
      main:
        port: 10062
        targetPort: 8888
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 20
