# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/wiserain/flexget
  pullPolicy: IfNotPresent
  tag: 3.19.19@sha256:bd5472d7c904f1e31d98c9aebd58c9e9495048908853752483e84de3be02a821
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            FG_LOG_LEVEL: info
            FG_LOG_FILE: flexget.log
            FG_WEBUI_PASSWD: "jLeT78KBDPW"
service:
  main:
    ports:
      main:
        port: 10174
        targetPort: 5050
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
