# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/aeonlucid/impostor
  tag: nightly@sha256:cdc3a89e3781393701dcc09a88191953257d004fe77fe8f177f34264ea0c1296
  pullPolicy: IfNotPresent
