# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/garethgeorge/backrest
  tag: v1.13.0@sha256:9c9966b5c285ec791a6b06cb4545fa0247424d05442e12f9558b4322d9f8a15f
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        port: 9898

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BACKREST_PORT: "0.0.0.0:{{ .Values.service.main.ports.main.port }}"
            BACKREST_DATA: /data
            BACKREST_CONFIG: /config/config.json
            XDG_CACHE_HOME: /cache
            TMPDIR: /tmp

persistence:
  data:
    enabled: true
    mountPath: /data
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  tmp:
    enabled: true
    type: emptyDir
    mountPath: /tmp
  userdata:
    enabled: false
    mountPath: /userdata
    readOnly: true
