# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/doplarr
  tag: "3.7.0@sha256:e7eb0b67ac23c8a7dc45a2b1ac3a63ecd6c504588319bd5dd01c05646f229501"
  pullPolicy: IfNotPresent
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            OVERSEERR__URL: ""
            DISCORD__MAX_RESULTS: 25
            DISCORD__REQUESTED_MSG_STYLE: ":plain"
            SONARR__URL: ""
            SONARR__QUALITY_PROFILE: ""
            SONARR__LANGUAGE_PROFILE: ""
            RADARR__URL: ""
            RADARR__QUALITY_PROFILE: ""
            PARTIAL_SEASONS: true
            LOG_LEVEL: ":info"
            OVERSEERR__API: ""
            OVERSEERR__DEFAULT_ID: ""
            SONARR__API: ""
            RADARR__API: ""
            DISCORD__ROLE_ID: ""
            DISCORD__TOKEN: ""
