# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/flood
  pullPolicy: IfNotPresent
  tag: "4.14.0@sha256:162a1eab034f14fff1ada3a3fb75ba33102192ad14d9ceedafbbc0b4cb7b5043"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /data
  config:
    enabled: true
    mountPath: /config
