# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/hauxir/imgpush
  tag: latest@sha256:46bf9c2b4fd3be05c3d3470e0dd480399fb69a1e9631a095e25edd3de655c962
persistence:
  storagecache:
    enabled: true
    mountPath: /cache
  storageimages:
    enabled: true
    mountPath: /images

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 5000
        protocol: tcp
        targetPort: 5000
