# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jeessy/ddns-go
  pullPolicy: IfNotPresent
  tag: v6.17.0@sha256:be70e8aea15f01038d7969c9bab97eb1a13c1f95facdc2a79d37b1e89b6b9f6c
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 9876
        protocol: http
        port: 10168
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  data:
    enabled: true
    mountPath: /root
