# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grocy
  tag: 4.6.0@sha256:ab39f3aeee92e121deafdd08966020dd05e3ed1dd323bab9e22988bd6d354572
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
