# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:8985315c11e81cb233a781ffa3486e07d01896eab3ac61e1f65c5d14422f4f3f
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-xfce@sha256:cbf4ee807472acdea1c8d8483c7801c2a0e9a6ad155d1c103fa6c39b5768fb7b
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-xfce@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-xfce@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:8985315c11e81cb233a781ffa3486e07d01896eab3ac61e1f65c5d14422f4f3f
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-mate@sha256:2b7afb3bdd3beca08eddcce04f5a7010a40576a3009967df738a9a587177c744
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-i3@sha256:ad1cb0dbc23163851e35ae2fdb27b61b9f843d590d539768cf25dc6758be21dc
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-openbox@sha256:5e91d5f7af31f51b601d2304b58e3e75ba03cb88bf4e970bff00941d9b296930
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-icewm@sha256:b06cdb635d332454be8f1b73e003c45e509600555160b2dad02667e4508095ca
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: tcp
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
updated: true
