# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.10.1-ultra-lite@sha256:bdcb90bd4269d9e4fead292508ee99c7913db017af2032530ecb9aabcfd1d6fe
fatImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.10.1-fat@sha256:8750f12bd61ca2d90b9723a06a08a36d49a83a22c946a227120926c53a928735
fullImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.10.1@sha256:950c596db26e0764f642def2fd4f9ee904ff2ac16d83fe621ff731b771d9b385
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18080
workload:
  main:
    podSpec:
      containers:
        main:
          # checkout the difference between the images.
          # https://github.com/Stirling-Tools/Stirling-PDF/blob/main/Version-groups.md
          imageSelector: image
          env:
            # enable to add login support
            DOCKER_ENABLE_SECURITY: false
            # uncomment to set the intial auth
            # default auth below
            # SECURITY_INITIALLOGIN_USERNAME: admin
            # SECURITY_INITIALLOGIN_PASSWORD: stirling
            # Download Calibre onto Stirling-PDF to enable PDF to/from book and advanced HTML conversion
            INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
            LANGS: en_US
persistence:
  configs:
    enabled: true
    mountPath: "/configs"
  tessdata:
    enabled: true
    mountPath: "/usr/share/tessdata"
  custom-files:
    enabled: true
    mountPath: "/customFiles"
  logs:
    enabled: true
    mountPath: "/logs"
