# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ddclient
  pullPolicy: IfNotPresent
  tag: 4.0.0@sha256:9187f128e2ac09e912b9af161030a4345c454a35a455f7e4b7198fdc4041006c
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
