# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/farmos/farmos
  tag: latest@sha256:a631191dbca24bd998818474f7397ebcb20a168f4a25c8f0489fcf25292a7fd5
persistence:
  sitesdirectory:
    enabled: true
    mountPath: /var/www/html/sites

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
