# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/agregarr/agregarr
  pullPolicy: IfNotPresent
  tag: v2.4.2@sha256:5f1390bc43fefbbfb67f38a7a8dd65b4086c1f187a37c8df5c6020a498e5d1b5
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 7171
        targetPort: 7171
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
