# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/filezilla
  tag: 3.68.1@sha256:dbb9568fa393d21cf58bc4dfbf403465a94395bfbc4a457d69b86f05306fd761
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:

service:
  main:
    ports:
      main:
        port: 10035
        protocol: http
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: false
