# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/glauth/glauth
  tag: latest@sha256:7c67e00d7e491a42b23972c9dc0863e517b3c2401d73ff79a8f15254b77be902
persistence:
  config:
    enabled: true
    mountPath: /app/config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  ldapport:
    enabled: true
    ports:
      ldapport:
        enabled: true
        port: 389
        protocol: tcp
        targetPort: 389
  ldapsport:
    enabled: true
    ports:
      ldapsport:
        enabled: true
        port: 636
        protocol: tcp
        targetPort: 636
  main:
    ports:
      main:
        port: 5555
        protocol: http
        targetPort: 5555
