# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/fletchto99/hexo-dev-blog
  tag: latest@sha256:2996de828eac705f5ed1d669cfecea25e5dc1c36e2d4acc88ac509006e29ea6a
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10306
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HEXO_PLUGINS: ""
