# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/budge
  tag: 0.0.9@sha256:0829248de7d26bc75a2197cb8839b9c2c55815fa174de503fa4d3e5a2238df86
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"
persistence:
  config:
    enabled: true
    mountPath: /config
