# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/openvscode-server
  pullPolicy: IfNotPresent
  tag: 1.109.5@sha256:454885e43de9ca6e10434b68ec25bc908582b651f4a36c65158ff4a94e213f32
# secretEnv:
#   CONNECTION_TOKEN: "somerandomstring"
#   CONNECTION_SECRET: ""
#   SUDO_PASSWORD: ""
service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10135
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
