# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/towfiqi/serpbear
  tag: latest@sha256:31bc71dc02a7d4efe4170e76eefac8be06077fb03d8d215919b602032dde3c38
persistence:
  data:
    enabled: true
    mountPath: /app/data

serpbear:
  api_key: ""
  app_url: http://localhost:10605
  password: secret
  session_duration: 24
  user: admin
service:
  main:
    ports:
      main:
        port: 10605
        protocol: http
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: serpbear-secret
