# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ctfd/ctfd
  tag: 3.8.4@sha256:da25249c41d19556573f11cf3c9fd887d47830310ae8d725ad443644a35b3455
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8000
        port: 10613

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            # filesystem  | s3
            UPLOAD_PROVIDER: filesystem
            # set storage locations.
            UPLOAD_FOLDER: "{{ .Values.persistence.uploads.mountPath }}"
            LOG_FOLDER: "{{ .Values.persistence.logs.mountPath }}"
            SECRET_KEY:
              secretKeyRef:
                name: ctfd-secrets
                key: SECRET_KEY
            REDIS_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: url
            MAIL_USEAUTH: false
            MAILFROM_ADDR: ""
            MAIL_SERVER: ""
            MAIL_PORT: 587
            MAIL_USERNAME: ""
            MAIL_PASSWORD: ""
            MAIL_TLS: false
            MAIL_SSL: false
            # CTFd will not load any plugins which may alleviate issues preventing CTFd from starting, default is false.
            SAFE_MODE: true
            REVERSE_PROXY: false
            # majorleaguecyber
            OAUTH_CLIENT_ID: ""
            OAUTH_CLIENT_SECRET: ""
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
redis:
  enabled: true
  redisUsername: default

persistence:
  uploads:
    enabled: true
    mountPath: "/uploads"
  logs:
    enabled: true
    mountPath: "/logs"
