# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/autobrr/autobrr
  pullPolicy: IfNotPresent
  tag: v1.79.0@sha256:5b8c29a86598907496af01ec75ef21f9c0e4e28ce9d6ae6496ef91c71543ec20

service:
  main:
    ports:
      main:
        protocol: http
        port: 7474

autobrr:
  # ERROR | DEBUG |INFO | WARN | TRACE
  log_level: DEBUG

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /config
  autobrr-config:
    enabled: true
    type: configmap
    objectName: autobrr-config
    mountPath: /config/config.toml
    subPath: config.toml
    readOnly: true
