# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/gabekangas/owncast
  tag: 0.2.5@sha256:0b4052dd2862921b35a5b4eb99219b0e85b2b9101e22d1e1079caaeaca5a8f92
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10088
        targetPort: 8080
  rtmp:
    enabled: true
    # externalTrafficPolicy: Local
    ports:
      rtmp:
        enabled: true
        port: 1935
        targetPort: 1935
persistence:
  config:
    enabled: true
    mountPath: "/app/data"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
