# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker
  pullPolicy: IfNotPresent
  tag: 29.4.3-dind@sha256:685b91dca8eab7de1dce1c303dbb7a763e4082d6a60db10968adf3295fbd2495
hostNetwork: true
securityContext:
  container:
    privileged: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
service:
  main:
    enabled: true
    type: ClusterIP
    ports:
      main:
        port: 2376
        type: https
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              initialDelaySeconds: 30
              type: tcp
            readiness:
              initialDelaySeconds: 30
              type: tcp
            startup:
              initialDelaySeconds: 30
              type: tcp
          env:
            DOCKER_TLS_CERTDIR: /certs
    type: StatefulSet
    replicas: 1
    strategy: RollingUpdate
persistence:
  docker-certs-ca:
    enabled: true
    mountPath: /config
volumeClaimTemplates:
  docker-certs-client:
    enabled: true
    mountPath: /certs/client
  docker:
    enabled: true
    mountPath: /var/lib/docker
