# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:b1d93513990251c4dbf233c29b1808a9f8d4fab0fdf1352beccadbfeec3581c8
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:df79511f4e167519415a9e8dd5907e49f3a3315479c8d06f65ac0cac55b9a824
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:d45dbd5e537cf0054fe93e4c834c1b4188da7b23355df47f498c8196696742f8
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:455c08199eea757a4b17d478880a682ec044f24ab0c586cf062a0f33ea7c7173
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:1546a68d85384394c307dec4d689b6acec992be4c0208ce27591186892d2fd56
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:a7163d72faae7eb1e1b0a28171c81fecf643aadaa12b75aedca9e749ac18f4ff
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:f3c78917184445fea357770a5dfbb64aec572638f0c56aafd1f66885d685b17e
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:294d397d7eaa1ef7e85a3ebf50efb32c0d731f2f28ea5c27c6f17a3a6307a8dd
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:b034890be79cc310ed6b4cdce1f9bed2da7d58df321b3734790257f903b85c36
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:d0069fc9827d2d8fe6b5bdef5d682ccbacf2c7b9de02051b53f4702bf6f94ac9
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:95eee64ecd9a309be72a12529ae452b64e9236346975747fee2eef93563f4428
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:39fb80999382158c0966e339977238e3ceadc63a3fdba554c777eaf1380312ef
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:43899fc81e09614829c624db1f8d14cd8263f46264ded888bdfe5b9db3929bc6
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:b7f85d7565df625cb9a8c8cf586c18f12cece86695e09e3a3439a47106db9584
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:0883b520eb2cdea6f83306dbe17faafdac0c217aca42e8b925ba67e42635eab8
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:3c12974952348cebe8e08b6940a8c483112a528396fb21b04dd176e2eb196b3f
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:32d2f78a5d2359569c8a625d080ed53ecead477ccca707c55c1afc9c6e0765f9
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:539248133c65e3d2d70dff67c8f9ff297186615487972491451210b1b9ee4d71
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:c40f887d9c03c5966debdfb8d9a6fb1a446cd5cb5dadde6195ca35a068742409
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:7f079e913b5696455889f795aff7c3acea1ab581de313ec63a797604c805d12d
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:440aebeafa9b9101d03f633be9a504d75917fcb7d6847842f67aa033c46f06f3
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:26f960e120edc080a12dfd76944acae0296eb7b69d79c437ef329836cc09e47a
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:871a0acf70fb754216f11b0c98fec51ab6871fc00f12a9a20eae0202cf7b1644
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:54d9079d38aee34063206fb5b233ea7c8801108756fb61aa0680eabdfad91dcd
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
