# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/requarks/wiki
  tag: 2.5.314@sha256:68f0d1848261ae76492ba358e30a96a76fed5d97a3fff381656082bf90f70d7e
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10045
        targetPort: 3000
cnpg:
  main:
    enabled: true
    user: wikijs
    database: wikijs
# /wiki/data is a temporary dir. Without mounting as emptyDir it's only writable by root.
# https://docs.requarks.io/en/install/config#data-paths
persistence:
  wikicache:
    enabled: true
    mountPath: "/wiki/data/"
    type: emptyDir

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/healthz"
            readiness:
              path: "/healthz"
            startup:
              path: "/healthz"
          env:
            DB_TYPE: "postgres"
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_USER: "{{ .Values.cnpg.main.user }}"
            DB_PORT: "5432"
            DB_PASS:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
