# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/mstream
  pullPolicy: IfNotPresent
  tag: 6.8.1@sha256:8788c77a98c8fba14fef306a54816ff45b392de9ac1484bbc2ad9b6ffd619c9e
service:
  main:
    ports:
      main:
        port: 10041
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
