# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/foxxmd/multi-scrobbler
  tag: latest@sha256:aecbf754a18c2ddc5d9bcf6385316a63aeae685f4106e76c25ab9d2c26c0f550
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9078
        targetPort: 9078

persistence:
  config:
    enabled: true
    mountPath: /config
