# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ich777/steamcmd
  tag: conanexiles@sha256:fed82b7c95bada0cf9d3a116b0f529fef972f425c9b1d4dd4b4bf27168763c7a
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  gameport1:
    enabled: true
    ports:
      gameport1:
        enabled: true
        port: 7778
        protocol: udp
        targetPort: 7778
  main:
    ports:
      main:
        port: 7777
        protocol: udp
        targetPort: 7777
  steamport:
    enabled: true
    ports:
      steamport:
        enabled: true
        port: 27015
        protocol: udp
        targetPort: 27015
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GAME_ID: "443030"
            GAME_PARAMS: ""
            PASSWRD: ""
            USERNAME: ""
            VALIDATE: "false"
            WS_CONTENT: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
