# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/it-tools
  pullPolicy: IfNotPresent
  tag: 2024.10.22@sha256:8966fde732b21b884893358c48fdcefcb5bb6d2233a6fcb06c5f4dcb1b7f637d
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18082
persistence:
  cache:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
  config:
    enabled: true
    type: emptyDir
    mountPath: /config
