# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/actualbudget/actual
  pullPolicy: IfNotPresent
  tag: 26.5.2@sha256:1aeeb3985db55556e716dec25e08f6ce09308c2571b65cddbc6746ee6d5e0d45
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10293
        protocol: http
        targetPort: 5006
persistence:
  data:
    enabled: true
    mountPath: /data
