# yaml-language-server: $schema=./values.schema.json

image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java25@sha256:5476619d049f4c0e2764532b345da1db4c154b4294bcc16d9c3b8d5f4b0d9923
  pullPolicy: Always

# ---- Java 25 ----
j25jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java25-jdk@sha256:8c951a26301283b9a24e9b355fa9546c2943d9c97d24e3c6ba4cef3a1d2ca7b8
  pullPolicy: Always

# ---- Java 21 (Recommended for modern MC versions) ----
j21Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java21@sha256:3abc3239c3565915aa26a4dc6bd9aa2944dc2ac4e2c485f496b58456620478b8
  pullPolicy: Always

j21alpineImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java21-alpine@sha256:d5634355e78f511c89021d41316ee6f154c4ff6809aef419be76a56365c9d47f
  pullPolicy: Always

j21jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java21-jdk@sha256:83b6b3855abbe3eb67932672df0d0abeff5c0a25f9c87a8f0a150c597f623a1f
  pullPolicy: Always

# ---- Java 17 (Safe & Supported) ----
j17Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java17@sha256:76c8d92cc93854838543cbbadcb5522f1d325d97882d4e9753005d53c228176e
  pullPolicy: Always

j17jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2024.6.1-java17-jdk@sha256:2c43fcede436aff9f50b1adf4448d55d221651be471ef41412232c141bfa89f6
  pullPolicy: Always

# ---- Java 16 ----
j16Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java16@sha256:0adef2589fc3b43890184ce57ac4b80cb97baad52f390143cbb5906305700797
  pullPolicy: Always

# ---- Java 11 ----
j11Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java11@sha256:7eb42b8855596a8943eeddeac54c8fff387be67cf95b242fa3ed156f843971c9
  pullPolicy: Always

# ---- Java 8 (Use plain java8 only) ----
j8Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.5.2-java8@sha256:0e10897886a27232a96985a08f27d26fb0c6f30dcd262256e5ccbd6a7c5b5607
  pullPolicy: Always

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        protocol: tcp
        port: 25565
      query:
        enabled: true
        protocol: udp
        port: 25565
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25575
  ssh:
    enabled: true
    ports:
      ssh:
        enabled: true
        protocol: tcp
        targetPort: 2222
        port: 2222

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - mc-health
            readiness:
              enabled: true
              type: exec
              command:
                - mc-health
            startup:
              enabled: true
              type: exec
              command:
                - mc-health
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            ENABLE_QUERY: "true"
            ENABLE_SSH: "false"
            EULA: "TRUE"
            GUI: "FALSE"
            OVERRIDE_SERVER_PROPERTIES: true
            VERSION: "LATEST"
            TYPE: "VANILLA"
            DIFFICULTY: easy
            MAX_PLAYERS: 20
            MAX_WORLD_SIZE: 10000
            ALLOW_NETHER: true
            ANNOUNCE_PLAYER_ACHIEVEMENTS: true
            ENABLE_COMMAND_BLOCK: false
            FORCE_GAMEMODE: false
            GENERATE_STRUCTURES: true
            HARDCORE: false
            MAX_BUILD_HEIGHT: 256
            MAX_TICK_TIME: 60000
            SPAWN_ANIMALS: true
            SPAWN_MONSTERS: true
            SPAWN_NPCS: true
            VIEW_DISTANCE: 16
            MODE: survival
            MOTD: "Welcome to Minecraft on TrueNAS Scale!"
            PVP: false
            LEVEL_TYPE: DEFAULT
            LEVEL: world
            ONLINE_MODE: true
            MEMORY: 2048M
            RCON_PASSWORD: "secretrconpass"
            # PACKWIZ_URL: ""
            # CUSTOM_SERVER: ""
            # QUILT_LOADER_VERSION: ""
            # QUILT_LAUNCHER: ""
            # QUILT_LAUNCHER_URL: ""
            # PUFFERFISH_BUILD: "lastSuccessfulBuild"
            # FORGEVERSION: ""
            # FORGE_INSTALLER: ""
            # FORGE_INSTALLER_URL: ""
            # FABRIC_LOADER_VERSION: ""
            # FABRIC_INSTALLER: ""
            # FABRIC_INSTALLER_URL: ""
            # SPIGOT_DOWNLOAD_URL: ""
            # BUILD_FROM_SOURCE: false
            # BUKKIT_DOWNLOAD_URL: ""
            # PAPERBUILD: ""
            # PAPER_DOWNLOAD_URL: ""
            # AIRPLANE_BUILD: "lastSuccessfulBuild"
            # MAGMA_CHANNEL: "stable"
            # MOHIST_BUILD: ""
            # CANYON_BUILD: ""
            # SPONGEBRANCH: "STABLE"
            # SPONGEVERSION: ""
            # LIMBO_BUILD: "LATEST"
            # LIMBO_SCHEMA_FILENAME: "default.schem"
            # CRUCIBLE_RELEASE: "latest"
            # FTB_MODPACK_ID: ""
            # FTB_MODPACK_VERSION_ID: ""
            # CF_SERVER_MOD: ""
            # CF_BASE_DIR: ""
            # USE_MODPACK_START_SCRIPT: true
            # FTB_LEGACYJAVAFIXER: false
            # WHITELIST: ""
            # OPS: ""
            # ICON: ""
            # SEED: ""
            # GENERATOR_SETTINGS: ""
            # WORLD: ""
            # FORCE_REDOWNLOAD: false
            # USE_FLARE_FLAGS: false
            # USE_AIKAR_FLAGS: true
            # USE_SIMD_FLAGS: false
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # CF_API_KEY
            # CF_PAGE_URL
            # CF_SLUG
            # CF_EXCLUDE_INCLUDE_FILE
            # CF_EXCLUDE_MODS
            # CF_FORCE_INCLUDE_MODS
            # CF_FORCE_SYNCHRONIZE
            # CF_OVERRIDES_SKIP_EXISTING
            # CF_PARALLEL_DOWNLOADS
            # CF_SET_LEVEL_FROM

persistence:
  data:
    enabled: true
    mountPath: /data
