# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/shlinkio/shlink-web-client
  pullPolicy: IfNotPresent
  tag: 4.7.1@sha256:acc95a754a52d2a2aa4e74da6f722180e5b209902f0f0aad7cd9df33d4b4fc6f
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10154
        protocol: http

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SHLINK_SERVER_URL: ""
            SHLINK_SERVER_API_KEY: ""
            SHLINK_SERVER_NAME: ""
