# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:2eebdc6f5b0e65845ff8e9e44b54f55fd137154848ff0924dd5d79f68def9721
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
