annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: productivity
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 5.10.0
dependencies:
  - name: common
    version: 29.3.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 18.3.1
    repository: oci://oci.trueforge.org/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: true
description: Matomo is the leading Free/Libre open analytics platform
home: https://truecharts.org/charts/stable/matomo
icon: https://truecharts.org/img/hotlink-ok/chart-icons/matomo.webp
keywords:
  - analytics
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: matomo
sources:
  - https://gallery.ecr.aws/bitnami/matomo
  - https://github.com/bitnami/bitnami-docker-matomo
  - https://github.com/matomo-org/matomo
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/matomo
type: application
version: 19.8.3

