# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/duplicati
  tag: 2.3.0@sha256:16ff282c18d3e5819a6c3338ced6ee9300316eb6a5cab7433e603d9f65ee9337
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8200
        targetPort: 8200
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            DUPLICATI__WEBSERVICE_PASSWORD: "SuperSecretPassword"
            SETTINGS_ENCRYPTION_KEY: "real_encryption_key"
            # DOTNET_SYSTEM_IO_DISABLEFILELOCKING: true

persistence:
  config:
    enabled: true
    mountPath: /data
