# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/balabit/syslog-ng
  pullPolicy: IfNotPresent
  tag: 4.11.0@sha256:04cbac1d62435feac432ab04093ee4c737116bdd8a6cead96a40db377608415c
service:
  main:
    ports:
      main:
        targetPort: 601
        port: 6601
  syslog-udp:
    enabled: true
    ports:
      syslog-udp:
        enabled: true
        protocol: udp
        targetPort: 514
        port: 5514
  syslog-tls:
    enabled: true
    ports:
      syslog-tls:
        enabled: true
        targetPort: 6514
        port: 6514
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
