# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/ixsystems/truecommand
  pullPolicy: IfNotPresent
  tag: 3.3.0@sha256:35a6bb629397c70b4fa79426df5bdd548d5bc0c283bbf592e4394ba3b54c8761
service:
  main:
    ports:
      main:
        port: 10031
        targetPort: 80
persistence:
  data:
    enabled: true
    mountPath: "/data"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
