# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/bitnamisecure/memcached
  pullPolicy: IfNotPresent
  tag: latest@sha256:103b56de2b93594dc95ba65ae7b9cb9725f65113f897fb04b2dbd48c82540580

service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211
configmap:
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
    data:
      memcached.json: >-
        {{ .Files.Get "dashboard.json" | indent 8 }}
