# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/librespeed
  tag: 6.1.0@sha256:ca10b086a4fbe70ca9d74bc7acbedb9f3ff188d1cf1f67486adac162ffb993c7
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10016
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
