# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/pwndrop
  pullPolicy: IfNotPresent
  tag: 1.0.1@sha256:af5cc64c7f88162c26bb446ea226ce6bc19dc137333e08d17a4e8f68d24016e8
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10149
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
