# yaml-language-server: $schema=./values.schema.json
image:
  repository: lscr.io/linuxserver/mylar3
  tag: version-v0.9.0@sha256:b938b5bbfd7d270f0c7dc4c7e9257bacf1b97a83519648a1baa044f4ebac5efd
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
