# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/dgtlmoon/changedetection.io
  pullPolicy: IfNotPresent
  tag: 0.55.3@sha256:2d0030e12494be9ebf6a6ebbbad46afe5763f498bbfefe9ebb7f0bf6be3ca5dc

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5000
        port: 5000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BASE_URL: ""
            USE_X_SETTINGS: true
            HIDE_REFERER: true
            FETCH_WORKERS: 10

persistence:
  datastore:
    enabled: true
    mountPath: "/datastore"
