# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/tinymediamanager/tinymediamanager
  tag: 5.2.12@sha256:5cb043b0558e29429ae07a369f5211b9f4c13db5e10d0ee4324d55280542c656
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10179
        targetPort: 4000
persistence:
  data:
    enabled: true
    mountPath: "/data"
  movies:
    enabled: true
    mountPath: "/media/movies"
  tvshows:
    enabled: true
    mountPath: "/media/tvshows"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
