# yaml-language-server: $schema=./values.schema.json
image:
  repository: registry
  pullPolicy: IfNotPresent
  tag: 3@sha256:85347ed2ecde64161c7a4788a4d7d3dcc9d6f86f7be95834022e3c6a423a945a
service:
  main:
    ports:
      main:
        port: 10096
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
