# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/digikam
  pullPolicy: IfNotPresent
  tag: 9.0.0@sha256:c5556056904783abdbea83e24c06a931af5e621a41bb1394c450a721548a922a
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10033
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
