# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/fluidd-core/fluidd
  tag: v1.37.0@sha256:3abe4b5a232d54804f967daeee340ff8f8f9a0bdb1a117c2817a7679e8054048
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10224
        targetPort: 80
