annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: library
  trueforge.org/category: unsorted
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: library
apiVersion: v2
appVersion: unknown
dependencies:
  - name: common
    version: '*'
    repository: file://../common/
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Helper chart to test different use cases of the common library
home: https://truecharts.org/charts/library/common-test
icon: https://truecharts.org/img/hotlink-ok/chart-icons/common-test.webp
keywords:
  - common-test
  - truecharts
  - common
  - test
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: common-test
sources:
  - https://github.com/trueforge-org/truecharts/tree/master/charts/library/common-test
type: application
version: 1.0.0

