# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/beryju/gravity
  tag: v0.33.0@sha256:850e7d9a909f659a16f1c134c53efda23795a60a2d74fccb8b3b68c56b79db59
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8008
        port: 8008
  dns:
    enabled: true
    ports:
      dns-tcp:
        enabled: true
        targetPort: 53
        port: 53
      dns-udp:
        enabled: true
        protocol: udp
        targetPort: 53
        port: 53

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            INSTANCE_IP: "127.0.0.1"
            ADMIN_PASSWORD: "password"
            INSTANCE_IDENTIFIER: "truecharts-dns-gravity"
            BOOTSTRAP_ROLES: "dns;api;etcd;discovery;backup;monitoring;tsdb"
            ADMIN_TOKEN:
              secretKeyRef:
                name: gravity-secret
                key: ADMIN_TOKEN
            INSTANCE_LISTEN: "0.0.0.0"

persistence:
  data:
    enabled: true
    mountPath: "/data"
