# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/dlandon/z80pack
  tag: latest@sha256:458c16b56df099148130e776ea40537d0e3e49d4d9c5dd2c068550f238ea149b
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4200
        protocol: tcp
        targetPort: 4200
