# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/chroma-core/chroma
  pullPolicy: IfNotPresent
  tag: 1.5.9@sha256:1e0b73a187a28757c572acba508c46f48c9e8b0acaf5c20e6d95cdedce1acdf6

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8000
        port: 10690

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/api/v2/heartbeat"
            readiness:
              path: "/api/v2/heartbeat"
            startup:
              path: "/api/v2/heartbeat"
          env:
            IS_PERSISTENT: true

persistence:
  config:
    enabled: true
    mountPath: "/chroma/chroma"
